#!/usr/bin/env node

const fs = require("fs");
const path = require("path");

function fail(msg) {
  console.error(`[vocab-version] ${msg}`);
  process.exit(1);
}

function info(msg) {
  console.log(`[vocab-version] ${msg}`);
}

function pad2(n) {
  return String(n).padStart(2, "0");
}

function nowIso() {
  return new Date().toISOString();
}

function parseArgs(argv) {
  const args = argv.slice(2);
  const cmd = args[0];
  const opts = {};

  for (let i = 1; i < args.length; i++) {
    const cur = args[i];
    if (!cur.startsWith("--")) continue;
    const key = cur.slice(2);
    const next = args[i + 1];
    if (!next || next.startsWith("--")) {
      opts[key] = true;
      continue;
    }
    opts[key] = next;
    i++;
  }
  return { cmd, opts };
}

function resolvePath(inputPath, cwd) {
  if (!inputPath) return null;
  return path.isAbsolute(inputPath) ? inputPath : path.resolve(cwd, inputPath);
}

function readJson(filePath) {
  const raw = fs.readFileSync(filePath, "utf8");
  return JSON.parse(raw);
}

function writeJson(filePath, data) {
  const dir = path.dirname(filePath);
  fs.mkdirSync(dir, { recursive: true });
  fs.writeFileSync(filePath, `${JSON.stringify(data, null, 2)}\n`, "utf8");
}

function normalizeWord(raw) {
  const m = String(raw || "").match(/[A-Za-z][A-Za-z'-]*/);
  return m ? m[0].toLowerCase() : null;
}

function sanitizeMap(raw) {
  if (!raw || typeof raw !== "object" || Array.isArray(raw)) return {};
  const out = {};
  for (const [k, v] of Object.entries(raw)) {
    if (typeof k !== "string" || typeof v !== "string") continue;
    const nk = normalizeWord(k);
    const nv = v.trim();
    if (!nk || !nv) continue;
    out[nk] = nv;
  }
  return out;
}

function sanitizeList(raw) {
  if (!Array.isArray(raw)) return [];
  const out = [];
  const seen = new Set();
  for (const item of raw) {
    const nk = normalizeWord(item);
    if (!nk || seen.has(nk)) continue;
    seen.add(nk);
    out.push(nk);
  }
  return out;
}

function asVocabularyMap(input, baseMap) {
  if (!input || typeof input !== "object" || Array.isArray(input)) return {};

  if (Object.prototype.hasOwnProperty.call(input, "vocab")) {
    return sanitizeMap(input.vocab);
  }

  if (
    Object.prototype.hasOwnProperty.call(input, "custom_vocab") ||
    Object.prototype.hasOwnProperty.call(input, "deleted_vocab")
  ) {
    const custom = sanitizeMap(input.custom_vocab);
    const deleted = new Set(sanitizeList(input.deleted_vocab));
    const merged = { ...(baseMap || {}), ...custom };
    for (const w of deleted) delete merged[w];
    return merged;
  }

  return sanitizeMap(input);
}

function sortedMap(mapObj) {
  const keys = Object.keys(mapObj).sort((a, b) => a.localeCompare(b));
  const out = {};
  for (const k of keys) out[k] = mapObj[k];
  return out;
}

function yearWeekLabel(dateObj) {
  const d = new Date(Date.UTC(dateObj.getUTCFullYear(), dateObj.getUTCMonth(), dateObj.getUTCDate()));
  const dayNum = d.getUTCDay() || 7;
  d.setUTCDate(d.getUTCDate() + 4 - dayNum);
  const yearStart = new Date(Date.UTC(d.getUTCFullYear(), 0, 1));
  const weekNo = Math.ceil(((d - yearStart) / 86400000 + 1) / 7);
  return `${d.getUTCFullYear()}-W${pad2(weekNo)}`;
}

function yearMonthLabel(dateObj) {
  return `${dateObj.getUTCFullYear()}-${pad2(dateObj.getUTCMonth() + 1)}`;
}

function makeSnapshotName(cadence, note) {
  const now = new Date();
  const prefix = cadence === "monthly" ? yearMonthLabel(now) : yearWeekLabel(now);
  const slug = note
    ? String(note)
        .toLowerCase()
        .replace(/[^a-z0-9]+/g, "-")
        .replace(/^-+|-+$/g, "")
        .slice(0, 32)
    : "snapshot";
  return `${prefix}-${slug || "snapshot"}.json`;
}

function usage() {
  console.log(`Usage:
  node scripts/vocab-version.js snapshot --input <file> --cadence <weekly|monthly> [--note <text>] [--base <file>] [--out <dir>]
  node scripts/vocab-version.js diff --from <file> --to <file> [--base <file>]
  node scripts/vocab-version.js promote --from <file> [--target <file>] [--backup]

Input formats supported:
  1) plain vocabulary map: {"algorithm":"..."}
  2) exported bundle: {"custom_vocab": {...}, "deleted_vocab": [...]}
  3) snapshot file generated by this tool: {"meta": {...}, "vocab": {...}}
`);
}

function ensureFile(filePath, label) {
  if (!filePath || !fs.existsSync(filePath)) {
    fail(`${label} not found: ${filePath || "(empty)"}`);
  }
}

function cmdSnapshot(opts, cwd) {
  const inputPath = resolvePath(opts.input, cwd);
  ensureFile(inputPath, "input");

  const cadence = opts.cadence;
  if (cadence !== "weekly" && cadence !== "monthly") {
    fail("snapshot requires --cadence weekly|monthly");
  }

  const basePath = resolvePath(opts.base || "vocabulary.json", cwd);
  ensureFile(basePath, "base");

  const outDir = resolvePath(opts.out || "vocab_versions", cwd);
  const note = opts.note ? String(opts.note).trim() : "";

  const baseMap = sanitizeMap(readJson(basePath));
  const input = readJson(inputPath);
  const vocab = sortedMap(asVocabularyMap(input, baseMap));

  const snapshot = {
    meta: {
      created_at: nowIso(),
      cadence,
      note: note || null,
      source_file: path.relative(cwd, inputPath),
      base_file: path.relative(cwd, basePath),
      word_count: Object.keys(vocab).length,
      tool: "scripts/vocab-version.js",
    },
    vocab,
  };

  const fileName = makeSnapshotName(cadence, note);
  const targetPath = path.join(outDir, cadence, fileName);
  writeJson(targetPath, snapshot);
  info(`snapshot created: ${path.relative(cwd, targetPath)} (${snapshot.meta.word_count} words)`);
}

function diffMaps(fromMap, toMap) {
  const fromKeys = new Set(Object.keys(fromMap));
  const toKeys = new Set(Object.keys(toMap));

  const added = [];
  const removed = [];
  const changed = [];

  for (const k of toKeys) {
    if (!fromKeys.has(k)) {
      added.push(k);
      continue;
    }
    if (fromMap[k] !== toMap[k]) {
      changed.push(k);
    }
  }

  for (const k of fromKeys) {
    if (!toKeys.has(k)) removed.push(k);
  }

  added.sort((a, b) => a.localeCompare(b));
  removed.sort((a, b) => a.localeCompare(b));
  changed.sort((a, b) => a.localeCompare(b));
  return { added, removed, changed };
}

function cmdDiff(opts, cwd) {
  const fromPath = resolvePath(opts.from, cwd);
  const toPath = resolvePath(opts.to, cwd);
  ensureFile(fromPath, "from");
  ensureFile(toPath, "to");

  const basePath = resolvePath(opts.base || "vocabulary.json", cwd);
  ensureFile(basePath, "base");

  const baseMap = sanitizeMap(readJson(basePath));
  const fromMap = asVocabularyMap(readJson(fromPath), baseMap);
  const toMap = asVocabularyMap(readJson(toPath), baseMap);
  const diff = diffMaps(fromMap, toMap);

  info(`from: ${path.relative(cwd, fromPath)} (${Object.keys(fromMap).length})`);
  info(`to  : ${path.relative(cwd, toPath)} (${Object.keys(toMap).length})`);
  info(`added=${diff.added.length}, removed=${diff.removed.length}, changed=${diff.changed.length}`);

  if (diff.added.length) {
    console.log("\n[Added]");
    for (const k of diff.added) console.log(`+ ${k}: ${toMap[k]}`);
  }
  if (diff.removed.length) {
    console.log("\n[Removed]");
    for (const k of diff.removed) console.log(`- ${k}: ${fromMap[k]}`);
  }
  if (diff.changed.length) {
    console.log("\n[Changed]");
    for (const k of diff.changed) {
      console.log(`* ${k}`);
      console.log(`  from: ${fromMap[k]}`);
      console.log(`  to  : ${toMap[k]}`);
    }
  }
}

function backupFileIfNeeded(targetPath) {
  const stamp = nowIso().replace(/[:.]/g, "-");
  const backupPath = `${targetPath}.bak.${stamp}`;
  fs.copyFileSync(targetPath, backupPath);
  return backupPath;
}

function cmdPromote(opts, cwd) {
  const fromPath = resolvePath(opts.from, cwd);
  ensureFile(fromPath, "from");

  const targetPath = resolvePath(opts.target || "vocabulary.json", cwd);
  ensureFile(targetPath, "target");

  const baseMap = sanitizeMap(readJson(targetPath));
  const sourceMap = sortedMap(asVocabularyMap(readJson(fromPath), baseMap));

  if (opts.backup) {
    const backup = backupFileIfNeeded(targetPath);
    info(`backup created: ${path.relative(cwd, backup)}`);
  }

  writeJson(targetPath, sourceMap);
  info(`promoted ${Object.keys(sourceMap).length} words -> ${path.relative(cwd, targetPath)}`);
}

function main() {
  const cwd = process.cwd();
  const { cmd, opts } = parseArgs(process.argv);
  if (!cmd || cmd === "help" || cmd === "--help" || cmd === "-h") {
    usage();
    process.exit(0);
  }

  if (cmd === "snapshot") return cmdSnapshot(opts, cwd);
  if (cmd === "diff") return cmdDiff(opts, cwd);
  if (cmd === "promote") return cmdPromote(opts, cwd);

  fail(`unknown command: ${cmd}`);
}

main();
